import { createStore } from 'vuex'

export default createStore({
  state: {
    playlists: [
      "minute men",
      "brunettes know better",
      "adore and amor",
      "alien allegro",
      " lowkey indie",
      "don't listen to this at night",
      "a quick reaction",
      "the path to success",
      "great tragedy",
      "good hands"
    ]
    ,
    bgColors: [
      "bg-indigo-200",
      "bg-purple-200",
      "bg-pink-200",
      "bg-green-200",
      "bg-blue-200",
      "bg-red-200",
      "bg-blue-200",
      "bg-indigo-300",
      "bg-purple-300",
      "bg-pink-300",
      "bg-green-300",
      "bg-blue-300",
      "bg-red-300",
      "bg-blue-300",
      "bg-indigo-400",
      "bg-purple-400",
      "bg-pink-400",
      "bg-green-400",
      "bg-blue-400",
      "bg-red-400",
      "bg-blue-400",
      "bg-indigo-500",
      "bg-purple-500",
      "bg-pink-500",
      "bg-green-500",
      "bg-blue-500",
      "bg-red-500",
      "bg-blue-500",
      "bg-indigo-600",
      "bg-purple-600",
      "bg-pink-600",
      "bg-green-600",
      "bg-blue-600",
      "bg-red-600",
      "bg-blue-600",
      "bg-indigo-700",
      "bg-purple-700",
      "bg-pink-700",
      "bg-green-700",
      "bg-blue-700",
      "bg-red-700",
      "bg-blue-700",
      "bg-indigo-800",
      "bg-purple-800",
      "bg-pink-800",
      "bg-green-800",
      "bg-blue-800",
      "bg-red-800",
      "bg-blue-800",
      "bg-indigo-900",
      "bg-purple-900",
      "bg-pink-900",
      "bg-green-900",
      "bg-blue-900",
      "bg-red-900",
      "bg-blue-900",
    ],
    gradientColors: [
      "from-indigo-200",
      "from-purple-200",
      "from-pink-200",
      "from-green-200",
      "from-blue-200",
      "from-red-200",
      "from-blue-200",
      "from-indigo-300",
      "from-purple-300",
      "from-pink-300",
      "from-green-300",
      "from-blue-300",
      "from-red-300",
      "from-blue-300",
      "from-indigo-400",
      "from-purple-400",
      "from-pink-400",
      "from-green-400",
      "from-blue-400",
      "from-red-400",
      "from-blue-400",
      "from-indigo-500",
      "from-purple-500",
      "from-pink-500",
      "from-green-500",
      "from-blue-500",
      "from-red-500",
      "from-blue-500",
      "from-indigo-600",
      "from-purple-600",
      "from-pink-600",
      "from-green-600",
      "from-blue-600",
      "from-red-600",
      "from-blue-600",
      "from-indigo-700",
      "from-purple-700",
      "from-pink-700",
      "from-green-700",
      "from-blue-700",
      "from-red-700",
      "from-blue-700",
      "from-indigo-800",
      "from-purple-800",
      "from-pink-800",
      "from-green-800",
      "from-blue-800",
      "from-red-800",
      "from-blue-800",
      "from-indigo-900",
      "from-purple-900",
      "from-pink-900",
      "from-green-900",
      "from-blue-900",
      "from-red-900",
      "from-blue-900",
    ],
    genres: [
      "acoustic",
      "afrobeat",
      "alt-rock",
      "alternative",
      "ambient",
      "anime",
      "black-metal",
      "bluegrass",
      "blues",
      "bossanova",
      "brazil",
      "breakbeat",
      "british",
      "cantopop",
      "chicago-house",
      "children",
      "chill",
      "classical",
      "club",
      "comedy",
      "country",
      "dance",
      "dancehall",
      "death-metal",
      "deep-house",
      "detroit-techno",
      "disco",
      "disney",
      "drum-and-bass",
      "dub",
      "dubstep",
      "edm",
      "electro",
      "electronic",
      "emo",
      "folk",
      "forro",
      "french",
      "funk",
      "garage",
      "german",
      "gospel",
      "goth",
      "grindcore",
      "groove",
      "grunge",
      "guitar",
      "happy",
      "hard-rock",
      "hardcore",
      "hardstyle",
      "heavy-metal",
      "hip-hop",
      "holidays",
      "honky-tonk",
      "house",
      "idm",
      "indian",
      "indie",
      "indie-pop",
      "industrial",
      "iranian",
      "j-dance",
      "j-idol",
      "j-pop",
      "j-rock",
      "jazz",
      "k-pop",
      "kids",
      "latin",
      "latino",
      "malay",
      "mandopop",
      "metal",
      "metal-misc",
      "metalcore",
      "minimal-techno",
      "movies",
      "mpb",
      "new-age",
      "new-release",
      "opera",
      "pagode",
      "party",
      "philippines-opm",
      "piano",
      "pop",
      "pop-film",
      "post-dubstep",
      "power-pop",
      "progressive-house",
      "psych-rock",
      "punk",
      "punk-rock",
      "r-n-b",
      "rainy-day",
      "reggae",
      "reggaeton",
      "road-trip",
      "rock",
      "rock-n-roll",
      "rockabilly",
      "romance",
      "sad",
      "salsa",
      "samba",
      "sertanejo",
      "show-tunes",
      "singer-songwriter",
      "ska",
      "sleep",
      "songwriter",
      "soul",
      "soundtracks",
      "spanish",
      "study",
      "summer",
      "swedish",
      "synth-pop",
      "tango",
      "techno",
      "trance",
      "trip-hop",
      "turkish",
      "work-out",
      "world-music",
    ],

  },
  mutations: {
  },
  actions: {
  },
  getters: {
    getPlaylists: state => {
      return state.playlists
    },
    getBgColors: state => {
      return state.bgColors
    },
    getGradientColors: state => {
      return state.gradientColors
    },
    getGenres: state => {
      return state.genres
    },
    getRandomBgColor: state =>  {
      return state.bgColors[parseInt(Math.random() * state.bgColors.length)];
    },
  },
  modules: {
  }
})
